import Header from "@components/Header";
import { store } from "@redux/store";
import { Poppins } from "next/font/google";
import { Providers } from "@redux/providers/toposProvider";
import "../styles/globals.css";

const inter = Poppins({
  weight: ["100", "300", "500", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body >
        <Providers store={store}>
          <div className={`${inter.className} antialiased `}>
            <Header />
            <div className="bodyContainer">
            {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
